Repository sampsyo/cs6120, pull requests merged in 2019-12, with the labels that each got.

#87 Project 2: Profile-Guided Code Layout
  content/blog/2019-10-23-profile-guided-code-layout/call-graph.png
  content/blog/2019-10-23-profile-guided-code-layout/code-layout-evaluation.png
  content/blog/2019-10-23-profile-guided-code-layout/index.md
  content/blog/2019-10-23-profile-guided-code-layout/main-block-graph.png
  content/blog/2019-10-23-profile-guided-code-layout/multiply-block-graph.png
Labels: project2

#89 Project 2: Loop Invariant Code Motion
  content/blog/2019-10-19-loop-invariant-code-motion/index.md
  content/blog/2019-10-19-loop-invariant-code-motion/natloop.jpeg
  content/blog/2019-10-19-loop-invariant-code-motion/plan.jpeg
  content/blog/2019-10-19-loop-invariant-code-motion/table.txt
Labels: project2

#104 Project 2: Partial Redundancy Elimination
  content/blog/2019-10-23-brilpre.md
Labels: project2

#165 Project 3: Partial Redundancy Elimination
  content/blog/2019-11-13-pre/chart2.png
  content/blog/2019-11-13-pre/index.md
Labels: project3

#158 Project 3: LLVM Function Inlining
  content/blog/2019-11-13-llvm-function-inlining/benchmarks.png
  content/blog/2019-11-13-llvm-function-inlining/index.md
Labels: project3

#172 Project 4: Quantum Vectorization
  content/blog/2019-12-18-qvec/index.md
Labels: project4

#173 Project 4: Data Streaming Simulation in LLVM
  content/blog/2019-12-18-heterocl-stream/DFG.png
  content/blog/2019-12-18-heterocl-stream/exec_time.png
  content/blog/2019-12-18-heterocl-stream/group.png
  content/blog/2019-12-18-heterocl-stream/index.md
  content/blog/2019-12-18-heterocl-stream/schedule1.png
  content/blog/2019-12-18-heterocl-stream/schedule2.png
  content/blog/2019-12-18-heterocl-stream/unit_test.png
Labels: project4

#162 Project 3: Posits
  content/blog/2019-12-03-posits/decimal-accuracy.png
  content/blog/2019-12-03-posits/denormalized.png
  content/blog/2019-12-03-posits/float-fun.png
  content/blog/2019-12-03-posits/holy-circle.png
  content/blog/2019-12-03-posits/index.md
  content/blog/2019-12-03-posits/mul-closure.png
  content/blog/2019-12-03-posits/not-denormalized.png
  content/blog/2019-12-03-posits/populated-circle.png
  content/blog/2019-12-03-posits/posit-fun.png
  content/blog/2019-12-03-posits/sqrt-losses.png
  content/blog/2019-12-03-posits/useed-circle.png
Labels: project3

#133 Project 3: Strength Reduction for Multiplication
  content/blog/2019-10-23-register-allocation/index.md
  content/blog/2019-10-23-register-allocation/reg_red.png
  content/blog/2019-11-13-multiplication-strength-reduction.md
Labels: project3

#175 Project 2: Bril Phase Ordering & Selection
  content/blog/2019-11-19-Bril-phase-selection-and-ordering/high_violin.png
  content/blog/2019-11-19-Bril-phase-selection-and-ordering/index.md
  content/blog/2019-11-19-Bril-phase-selection-and-ordering/low_violin.png
  content/blog/2019-11-19-Bril-phase-selection-and-ordering/mid_violin.png
Labels: project2

#82 Superblock Scheduling for Bril
  content/blog/2019-09-25-a-verification-backend.md
  content/blog/2019-10-24-superblock-scheduling.md
Labels: project2

#171 Project 4: FSM Generation for FuTIL
  .gitignore
  content/blog/2019-11-21-bug-finding/.DS_Store
  content/blog/2019-11-21-bug-finding/index.md
  content/blog/2019-12-13-futil-fsm/fib.png
  content/blog/2019-12-13-futil-fsm/flow.png
  content/blog/2019-12-13-futil-fsm/fsm.png
  content/blog/2019-12-13-futil-fsm/if_trace.png
  content/blog/2019-12-13-futil-fsm/index.md
  content/blog/2019-12-13-futil-fsm/while_trace.png
Labels: project4

#182 Project 4: An autoscheduler for Halide
  content/blog/2019-12-18-halide-autoscheduler/default.png
  content/blog/2019-12-18-halide-autoscheduler/deinline.png
  content/blog/2019-12-18-halide-autoscheduler/hoist-compute.png
  content/blog/2019-12-18-halide-autoscheduler/hoist-storage.png
  content/blog/2019-12-18-halide-autoscheduler/index.md
  content/blog/2019-12-18-halide-autoscheduler/inline.png
  content/blog/2019-12-18-halide-autoscheduler/lower-compute.png
  content/blog/2019-12-18-halide-autoscheduler/reorder.png
  content/blog/2019-12-18-halide-autoscheduler/semantics.png
Labels: project4

#183 Project 3: LLVM autovectorization
  content/blog/2019-11-13-llvm-autovec/index.md
Labels: project3

#179 Project 4: Internal Function Memoization
  content/blog/2019-12-20-Internal-Function-Memoization/fib.png
  content/blog/2019-12-20-Internal-Function-Memoization/fiblay.png
  content/blog/2019-12-20-Internal-Function-Memoization/index.md
  content/blog/2019-12-20-Internal-Function-Memoization/it_henri.png
  content/blog/2019-12-20-Internal-Function-Memoization/kat.png
  content/blog/2019-12-20-Internal-Function-Memoization/lin.png
  content/blog/2019-12-20-Internal-Function-Memoization/memo.png
  content/blog/2019-12-20-Internal-Function-Memoization/rec_henri.png
Labels: project4

#185 Project 4: Logical Indexing
  content/blog/2019-12-21-logical-indexing-on-HB/index.md
Labels: project4

#184 Project 4: Bril JIT with On-Stack Replacement
  content/blog/2019-12-18-bril-osr/ackermann.png
  content/blog/2019-12-18-bril-osr/fib_func_100.png
  content/blog/2019-12-18-bril-osr/fib_func_500.png
  content/blog/2019-12-18-bril-osr/index.md
  content/blog/2019-12-18-bril-osr/knn_100.png
  content/blog/2019-12-18-bril-osr/knn_500.png
Labels: project4
